[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "47a4a518f4fc8de6239acbcffb62c8359139d18f"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ade130469f5e84ace2fdb1d084a30d11ce5ecc8c58e05c13635add3d421f12c0"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "5da26dbdbf431ee15ff70d775217136ddf71426e"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "495ef0471b714037f784f448e8ab4e07a53b40e00acd99b3a8176e318f8ba64c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "7ed49ea0f38b51d08fd035f27c3faa49f1e935ce"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "c8267813c0603953d8c15ff4330a8753ec750f873f2b5a3b7f12ad4bf30d296d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "bbe74c94cdaefba3ba9ddf05ea8afcdfd5185e8a"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "76bf2c49eb381185c928194e1473bed2bb31bed73630f1027a2129d08f5b8946"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "f8164ec2da400d3eb5f2f8727e3356b144f7125b"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "af98952649dbd81be3ace70ee1d79c429b1cea07387eb07cdb8fcb3ea0709058"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "d71c60da1db0cf44bd013b9e56d9bc8ac3d7193e"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4802ad208b3a17f441666d1de6b864460dd10ae46be6eae65d4ba53c108b94f0"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "c97e75121fcae815465be97fc74b4a7d10d3b204"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "fd36f01c8fc39a9b511e0fe39fbfb2f58366d51cea4b69cd22e8210936680865"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "a3bf8973554eb67eb06606153989d4a4f12f2688"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "30266f0e3d6db601fefd43f93756a9cbfa6b66f5f6421f53ef283d14df4c46f3"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "dccaacd6feb1c29b65a7bdc2facd753f3a95f411"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a26101eb3f385451df5a9698b97fd15e5c1845f768cec487974d024ad8358f7d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "3dcb808fb86ed60099dc734d4c22dd70e8027496"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "cf7d50fa93976cc39850b8f4d51fd0cbc459f7e56fb50a70a623287e107b3dbc"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "d90b262299aadcd6565d441901bdcad552d16ca6"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "306437e7ade02982c763b9ff0a65cb335eb2b3e7f9e57d875fa4c42ac12bafb7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "a291556493c6f51eca91f49c08f395578898a642"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "2f40dc3a5827963eea192036555c248cf4b3bfead0c47b7dd6b6964f7ae5139f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "e5dd569ff7347262ac4b09c7fbc2cf6c0ecbfb47"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "76f3c09aba800e2284c07d2649b7cf87ab1f1d96b936b7759f802c598b23f120"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.4.0/vegaliteassets-2.4.0-x86_64-w64-mingw32.tar.gz"
